alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
domains:
- domain: ${DIGITALOCEAN_APP_DOMAIN}
  type: PRIMARY
  minimum_tls_version: "1.2"
envs:
  - key: ENV
    scope: RUN_TIME
    value: ${ENV}
  - key: POLYGONSCAN_API_KEY
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: ${POLYGONSCAN_API_KEY}
  - key: WEB3_INFURA_PROJECT_ID
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: ${WEB3_INFURA_PROJECT_ID}
name: ${DIGITALOCEAN_APP_NAME}
region: nyc
services:
  - environment_slug: python
    image:
      registry_type: DOCR
      repository: dash-apps
      tag: ${GITHUB_SHA}
    health_check:
      http_path: /
      initial_delay_seconds: 60
      timeout_seconds: 600
      period_seconds: 20
      success_threshold: 1
      failure_threshold: 20
    http_port: 8050
    routes:
      - path: /
    instance_count: 1
    instance_size_slug: basic-s
    name: carbon-dashboard
    run_command: gunicorn --worker-tmp-dir /dev/shm --timeout 120 src.apps.tco2_dashboard.app:server
    source_dir: /
