alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
domains:
  - domain: ${DIGITALOCEAN_APP_DOMAIN}
    type: PRIMARY
    minimum_tls_version: "1.2"
envs:
  - key: ENV
    scope: RUN_TIME
    value: ${ENV}
  - key: POLYGONSCAN_API_KEY
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: ${POLYGONSCAN_API_KEY}
  - key: WEB3_INFURA_PROJECT_ID
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: ${WEB3_INFURA_PROJECT_ID}
  - key: PREFECT_API_KEY
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: ${PREFECT_API_KEY}
  - key: PREFECT_API_URL
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: ${PREFECT_API_URL}
name: ${DIGITALOCEAN_APP_NAME}
region: nyc
services:
  - environment_slug: python
    image:
      registry_type: DOCR
      repository: dash-apps
      tag: ${GITHUB_SHA}
    health_check:
      http_path: /
      initial_delay_seconds: 60
      timeout_seconds: 1200
      period_seconds: 20
      success_threshold: 1
      failure_threshold: 20
    http_port: 8050
    routes:
      - path: /
    instance_count: 1
    instance_size_slug: ${DIGITALOCEAN_SIZE_SLUG}
    name: carbon-dashboard
    run_command: gunicorn --worker-tmp-dir /dev/shm --timeout ${GUNICORN_TIMEOUT} src.apps.tco2_dashboard.app:server
    source_dir: /
  - environment_slug: python
    image:
      registry_type: DOCR
      repository: dash-apps
      tag: ${GITHUB_SHA}
    health_check:
      http_path: /api/v1
      initial_delay_seconds: 60
      timeout_seconds: 1200
      period_seconds: 20
      success_threshold: 1
      failure_threshold: 20
    http_port: 8050
    routes:
      - path: /api/v1/
        preserve_path_prefix: true
    instance_count: 1
    instance_size_slug: basic-xs
    name: carbon-api
    run_command: gunicorn --workers=1 --threads=2 --worker-tmp-dir /dev/shm --timeout ${GUNICORN_TIMEOUT} src.apps.api.app:app
    source_dir: /
