version: "3.5"

services:
  treasury:
    # image: dash-apps
    build:
      context: ./
    working_dir: /src
    env_file: .env
    entrypoint: python
    command: ["-m", "src.apps.treasury.index"]
    ports:
      - 8050:8050
    volumes:
      - ./:/src

  # api:
  #   image: dash-apps
  #   working_dir: /src
  #   env_file: .env
  #   entrypoint: python
  #   command: ["-m", "src.apps.api.app"]
  #   ports:
  #     - 8051:8050
  #   volumes:
  #     - ./:/src